### ISSUE TITLE
can't run stuff as described in README

### ISSUE THREAD

**Issue by sandover** [kanaka/clojurescript#37]
I'm hoping to use this project to get some quick and dirty .js from .cljs in the context of a node project.  I can't run any of the examples, e.g. 

```
cd node
../bin/cljsc ../src/cljs/nodecljs.cljs > nodecljs.js
```

I get 

```
Exception in thread "main" java.lang.NoClassDefFoundError: clojure/main
Caused by: java.lang.ClassNotFoundException: clojure.main
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

There's no project.clj so lein deps can't be the answer. . . halp?

thanks.

**Comment by sandover** [comment]
Forgot about script/bootstrap -- my bad.

Suggestion: update the bootstrap script to Clojure 1.5.1
