### ISSUE TITLE
division symbol breaks namespaces atom (currently removed)

### ISSUE THREAD

**Issue by kanaka** [kanaka/clojurescript#6]
Currently, the / symbol is removed from the namespaces snapshot during compile. If it's added back in like this:

```
--- a/src/clj/cljs/compiler.clj
+++ b/src/clj/cljs/compiler.clj
@@ -784,8 +784,7 @@

 (defn ns-snap [ns]
   (let [nss1 (dissoc (get @ana/namespaces ns) :requires-macros)
-        nss2 (read-string (pr-str (update-in nss1
-                                             [:defs] dissoc '/)))]
+        nss2 (read-string (pr-str nss1))]
     (apply str
       (emit (ana/analyze (ana/empty-env)
         (list 'swap! 'cljs.core/namespaces 'assoc (list 'quote ns) (list 'quote nss2)))))))
```

Then the compile throws an exception:

```
Exception in thread "main" java.lang.RuntimeException: Invalid token: cljs.core//
        at clojure.lang.Util.runtimeException(Util.java:170)
        at clojure.lang.LispReader.interpretToken(LispReader.java:321)
```

Also, it's likely that in core.cljs, the namespace and name functions will need to be fixed once the above works. For example, (namespace 'cljs.core//) gives "cljs.core/" because it is looking for the last /.

**Comment by kanaka** [comment]
Fix in 282e356c892a355f05df446a169be7de399efd0a
